name: Terraform Workflow


# Trigger the workflow on push or pull requests to the main branch
on:
  push:
    branches:
      - mainbranch
  # pull_request:
  #   branches:
  #     - main

# env:
#  # verbosity setting for Terraform logs
#  # Credentials for deployment to AWS
#  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
 # aws-region: ap-south-1
 # AWS_REGION: 'us-east-1'
 
# Define the jobs to be executed
jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: sample_env

    # env:
      # aws-region: 'us-east-1'
      # TF_VERSION: '1.4.0'
      # TFLINT_VERSION: '0.46.1'  # Updated to a more recent version
      # TFSEC_VERSION: '1.28.1' 

    # Steps for the workflow
    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Setup Terraform environment (Install Terraform)
    # - name: Setup Terraform
    #   uses: hashicorp/setup-terraform@v2
    #   with:
    #     terraform_version: 1.9.0  # Specify the version of Terraform to use


    - name: Run command in specific directory
      run: |
          ls -la
          echo "Running commands in the target directory"
      working-directory: infra/terraform/
  
    # Configure AWS Credentials (if you're deploying on AWS)
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      # with: this is used when secrets are stored in github Repository secrets
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}  # Specify your AWS region

    # Initialize Terraform (Download modules, plugins, etc.)
    - name: Terraform Init
      run: terraform init
      working-directory: infra/terraform/

    # Run Terraform Plan to see changes
    - name: Terraform Plan
      run: terraform plan
      working-directory: infra/terraform/
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS-REGION: ${{ secrets.AWS_REGION }} 
        # AWS-REGION: ${{ env.aws-region }}

    # Apply changes (only for push events, not for pull requests)
    # - name: Terraform Apply
    #   # if: github.event_name == 'push'  # Run only on push
    #   run: terraform apply -auto-approve
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
